using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HugeArrayGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class HeavyArrayGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Эквивалент твоих 370 000 строк по 20 токенов = 7 400 000 реальных байт
            int totalBytes = 370000 * 20; 
            byte[] rawBinaryData = new byte[totalBytes];
            
            // Заполняем массив байтами (имитируем данные emoji)
            for (int i = 0; i < rawBinaryData.Length; i++) 
            {
                rawBinaryData[i] = 0xC0; 
            }

            // Кодируем массив в одну компактную Base64 строку
            string base64Data = Convert.ToBase64String(rawBinaryData);

            // Передаем в Roslyn только постобработку
            context.RegisterPostInitializationOutput(postInitContext =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("using System;");
                sb.AppendLine("namespace GeneratedNamespace;");
                sb.AppendLine("internal sealed class GeneratedHeavyData {");
                sb.AppendLine("    private static byte[] _cachedData;");
                sb.AppendLine("    public static ReadOnlySpan<byte> Data {");
                sb.AppendLine("        get {");
                sb.AppendLine("            if (_cachedData == null) {");
                // Roslyn прочитает эту гигантскую строку как ОДИН токен мгновенно и без затрат памяти!
                sb.AppendLine($"                string base64 = \"{base64Data}\";");
                sb.AppendLine("                _cachedData = Convert.FromBase64String(base64);");
                sb.AppendLine("            }");
                sb.AppendLine("            return _cachedData;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                // Передаем Roslyn оптимизированный код
                postInitContext.AddSource("GeneratedHeavyData.g.cs", sb.ToString());
            });
        }
    }
}