using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HugeArrayGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class HeavyArrayGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Регистрируем генерацию кода при старте сборки
            context.RegisterPostInitializationOutput(postInitContext =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("using System;");
                sb.AppendLine("namespace GeneratedNamespace;");
                sb.AppendLine("internal sealed class GeneratedHeavyData {");
                sb.AppendLine("    private static ReadOnlySpan<byte> Data => new byte[] {");

                // Генерируем 100,000 строк (для тестов в IDE этого хватит, чтобы заметить просадку)
                // Каждая строка — это 20 токенов (итого 2,000,000 токенов)
                int linesCount = 370000; 
                for (int i = 0; i < linesCount; i++)
                {
                    sb.AppendLine("        0xC0, 0x1D, 0x00, 0x00, 0x04, 0x77, 0x00, 0x00, 0x23, 0x77, 0x00, 0x00, 0x34, 0x77, 0x00, 0x00, 0x72, 0x77, 0x00, 0x00,");
                }

                sb.AppendLine("        0x6F, 0x6E, 0x67");
                sb.AppendLine("    };");
                sb.AppendLine("}");

                // Добавляем сгенерированный исходный код в компиляцию
                postInitContext.AddSource("GeneratedHeavyData.g.cs", sb.ToString());
            });
        }
    }
}