using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HugeArrayGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class HeavyArrayGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(postInitContext =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("using System;");
                sb.AppendLine("namespace GeneratedNamespace;");
                sb.AppendLine("public sealed class GeneratedHeavyData {");
                sb.AppendLine("    public static ReadOnlySpan<byte> Data => new byte[] {");

                // Every line is 20 tokens. So 100000 lines => 2 000 000 tokens
                int linesCount = 100000; 
                for (int i = 0; i < linesCount; i++)
                {
                    sb.AppendLine("        0xC0, 0x1D, 0x00, 0x00, 0x04, 0x77, 0x00, 0x00, 0x23, 0x77, 0x00, 0x00, 0x34, 0x77, 0x00, 0x00, 0x72, 0x77, 0x00, 0x00,");
                }

                sb.AppendLine("        0x6F, 0x6E, 0x67");
                sb.AppendLine("    };");
                sb.AppendLine("}");
                
                postInitContext.AddSource("GeneratedHeavyData.g.cs", sb.ToString());
            });
        }
    }
}